In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("treated_data/bank_train_treated.csv")
df

Unnamed: 0   age            job  marital  education default  balance  \
0               0  41.0     management   single   tertiary      no   4522.0   
1               1  42.0    blue-collar  married    primary     yes    398.0   
2               2  26.0        student   single  secondary      no    706.0   
3               3  54.0     management  married   tertiary      no      0.0   
4               4  43.0  self-employed  married  secondary      no    918.0   
...           ...   ...            ...      ...        ...     ...      ...   
39995       39995  43.0     management  married   tertiary      no  10000.0   
39996       39996  34.0    blue-collar  married    primary      no    357.0   
39997       39997  30.0     management   single   tertiary      no   4889.0   
39998       39998  40.0  self-employed  married   tertiary      no    271.0   
39999       39999  60.0      housemaid  married   tertiary      no    443.0   

      housing loan   contact  month  duration  campaign  pdays  previous  \
0          no   no  cellular      8        55       1.0     -1       0.0   
1         yes    n   unknown      5       251       4.0     -1       0.0   
2          no   no   unknown     10       118       1.0    105       2.0   
3          no    y  cellular     11       307       3.0     -1       0.0   
4         yes   no   unknown      5       193       1.0     -1       0.0   
...       ...  ...       ...    ...       ...       ...    ...       ...   
39995     yes   no  cellular     11       259       1.0     -1       0.0   
39996     yes   no   unknown      5       197       2.0     -1       0.0   
39997      no   no  cellular      8       545       2.0     -1       0.0   
39998     yes   no  cellular     11       124       3.0    102       4.0   
39999      no    n   unknown      6        60       1.0     -1       0.0   

      poutcome    y  
0      unknown   no  
1      unknown   no  
2        other   no  
3      unknown   no  
4      unknown   no  
...        ...  ...  
39995  unknown   no  
39996  unknown   no  
39997  unknown  yes  
39998  failure   no  
39999  unknown   no  

[40000 rows x 17 columns]

In [3]:
#Transformando features categóricas em numéricas utilizando LabelEncoder
categoricas = df.select_dtypes("object").columns
print(categoricas)

Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'poutcome', 'y'],
      dtype='object')


In [4]:
for i in range(len(categoricas)):
    le = LabelEncoder()
    df[categoricas[i]] = le.fit_transform(df[categoricas[i]])
    #print(df[categoricas[i]])
df


Unnamed: 0   age  job  marital  education  default  balance  housing  \
0               0  41.0    4        2          2        0   4522.0        0   
1               1  42.0    1        1          0        1    398.0        1   
2               2  26.0    8        2          1        0    706.0        0   
3               3  54.0    4        1          2        0      0.0        0   
4               4  43.0    6        1          1        0    918.0        1   
...           ...   ...  ...      ...        ...      ...      ...      ...   
39995       39995  43.0    4        1          2        0  10000.0        1   
39996       39996  34.0    1        1          0        0    357.0        1   
39997       39997  30.0    4        2          2        0   4889.0        0   
39998       39998  40.0    6        1          2        0    271.0        1   
39999       39999  60.0    3        1          2        0    443.0        0   

       loan  contact  month  duration  campaign  pdays  previous  poutcome  y  
0         1        0      8        55       1.0     -1       0.0         3  0  
1         0        2      5       251       4.0     -1       0.0         3  0  
2         1        2     10       118       1.0    105       2.0         1  0  
3         2        0     11       307       3.0     -1       0.0         3  0  
4         1        2      5       193       1.0     -1       0.0         3  0  
...     ...      ...    ...       ...       ...    ...       ...       ... ..  
39995     1        0     11       259       1.0     -1       0.0         3  0  
39996     1        2      5       197       2.0     -1       0.0         3  0  
39997     1        0      8       545       2.0     -1       0.0         3  1  
39998     1        0     11       124       3.0    102       4.0         0  0  
39999     0        2      6        60       1.0     -1       0.0         3  0  

[40000 rows x 17 columns]

In [5]:
X = df.copy().drop(columns=["y"])
Y = df["y"]

In [6]:
Y

0        0
1        0
2        0
3        0
4        0
        ..
39995    0
39996    0
39997    1
39998    0
39999    0
Name: y, Length: 40000, dtype: int64

In [7]:
X

Unnamed: 0   age  job  marital  education  default  balance  housing  \
0               0  41.0    4        2          2        0   4522.0        0   
1               1  42.0    1        1          0        1    398.0        1   
2               2  26.0    8        2          1        0    706.0        0   
3               3  54.0    4        1          2        0      0.0        0   
4               4  43.0    6        1          1        0    918.0        1   
...           ...   ...  ...      ...        ...      ...      ...      ...   
39995       39995  43.0    4        1          2        0  10000.0        1   
39996       39996  34.0    1        1          0        0    357.0        1   
39997       39997  30.0    4        2          2        0   4889.0        0   
39998       39998  40.0    6        1          2        0    271.0        1   
39999       39999  60.0    3        1          2        0    443.0        0   

       loan  contact  month  duration  campaign  pdays  previous  poutcome  
0         1        0      8        55       1.0     -1       0.0         3  
1         0        2      5       251       4.0     -1       0.0         3  
2         1        2     10       118       1.0    105       2.0         1  
3         2        0     11       307       3.0     -1       0.0         3  
4         1        2      5       193       1.0     -1       0.0         3  
...     ...      ...    ...       ...       ...    ...       ...       ...  
39995     1        0     11       259       1.0     -1       0.0         3  
39996     1        2      5       197       2.0     -1       0.0         3  
39997     1        0      8       545       2.0     -1       0.0         3  
39998     1        0     11       124       3.0    102       4.0         0  
39999     0        2      6        60       1.0     -1       0.0         3  

[40000 rows x 16 columns]

In [37]:
from sklearn.preprocessing import StandardScaler
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=1234)
X_train_scaled = StandardScaler().fit_transform(X_train)
X_test_scaled = StandardScaler().fit_transform(X_test)
models = []
predictions = []
scores = []
max_score = 0
index_max = 0
for i in range(1000):
    models.append(LogisticRegression(max_iter=i))#Testing newton-cg solver
    models[i].fit(X_train_scaled, Y_train)
    predictions.append(models[i].predict(X_test_scaled))
    scores.append(models[i].score(X_test_scaled, Y_test))
for i in range(len(models)):
    if scores[i] > max_score:
        max_score = scores[i]
        index_max = i
    print(scores[i], i)
print("Max score:", max_score, "Max_iter: ", index_max)

C:\Users\artda\miniconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\artda\miniconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_ite

0.8839166666666667 0
0.8839166666666667 1
0.88725 2
0.8881666666666667 3
0.8895 4
0.8908333333333334 5
0.89075 6
0.8905833333333333 7
0.8906666666666667 8
0.8909166666666667 9
0.8909166666666667 10
0.891 11
0.8909166666666667 12
0.8909166666666667 13
0.8909166666666667 14
0.8909166666666667 15
0.8909166666666667 16
0.8909166666666667 17
0.8909166666666667 18
0.8909166666666667 19
0.8909166666666667 20
0.8909166666666667 21
0.8909166666666667 22
0.8909166666666667 23
0.8909166666666667 24
0.8909166666666667 25
0.8909166666666667 26
0.8909166666666667 27
0.8909166666666667 28
0.8909166666666667 29
0.8909166666666667 30
0.8909166666666667 31
0.8909166666666667 32
0.8909166666666667 33
0.8909166666666667 34
0.8909166666666667 35
0.8909166666666667 36
0.8909166666666667 37
0.8909166666666667 38
0.8909166666666667 39
0.8909166666666667 40
0.8909166666666667 41
0.8909166666666667 42
0.8909166666666667 43
0.8909166666666667 44
0.8909166666666667 45
0.8909166666666667 46
0.8909166666666667 47
0

In [19]:
#Com o melhor modelo em mãos o aplicaremos no dataset de teste
best_model = models[index_max-100]
df_test = pd.read_csv("treated_data/bank_test.csv")
df_test

id   age            job   marital  education location default  \
0     40000  26.0  self-employed    single   tertiary    Porto      no   
1     40001  47.0     technician   married  secondary      NaN      no   
2     40002  35.0  self-employed   married   tertiary      NaN      no   
3     40003  54.0     technician  divorced  secondary      NaN      no   
4     40004  27.0    blue-collar    single  secondary    Braga      no   
...     ...   ...            ...       ...        ...      ...     ...   
5206  45206  38.0  administrator   married  secondary      NaN      no   
5207  45207  39.0      housemaid   married    primary   Lisboa      no   
5208  45208  46.0     technician   married  secondary  Amadora      no   
5209  45209   NaN     technician    single  secondary    Braga      no   
5210  45210  56.0    blue-collar   married  secondary      NaN      no   

      balance housing loan   contact  day month  duration  campaign  pdays  \
0      -101.0      no  yes  cellular   29   jan       172       1.0     -1   
1      1167.0     yes   no  cellular    2   feb       139       3.0     73   
2      2427.0      no   no  cellular   12   jul       210       3.0    158   
3         NaN      no   no  cellular   30   jan        86       1.0     -1   
4      -208.0     yes    n   unknown   21   may       127       2.0     -1   
...       ...     ...  ...       ...  ...   ...       ...       ...    ...   
5206   1767.0     yes   no  cellular   12   nov       893       7.0     -1   
5207    562.0      no   no  cellular   12   aug       234       2.0     -1   
5208      0.0      no   no   unknown   20   jun       625       1.0     -1   
5209   1195.0     yes   no  cellular   19   nov       187       6.0    188   
5210      NaN     yes   no   unknown    7   may       139       1.0     -1   

      previous poutcome  
0          0.0  unknown  
1          2.0  success  
2          7.0    other  
3          0.0  unknown  
4          0.0  unknown  
...        ...      ...  
5206       0.0  unknown  
5207       0.0  unknown  
5208       0.0  unknown  
5209       9.0  failure  
5210       0.0  unknown  

[5211 rows x 18 columns]

In [20]:
df_test.isna().sum()

id              0
age           166
job           156
marital        19
education       0
location     2762
default         0
balance       247
housing         0
loan            0
contact        90
day             0
month           0
duration        0
campaign      189
pdays           0
previous       39
poutcome        0
dtype: int64

In [21]:
ids = df_test["id"]
df_test.drop(columns=["id"], inplace=True)

In [22]:
df_test

age            job   marital  education location default  balance  \
0     26.0  self-employed    single   tertiary    Porto      no   -101.0   
1     47.0     technician   married  secondary      NaN      no   1167.0   
2     35.0  self-employed   married   tertiary      NaN      no   2427.0   
3     54.0     technician  divorced  secondary      NaN      no      NaN   
4     27.0    blue-collar    single  secondary    Braga      no   -208.0   
...    ...            ...       ...        ...      ...     ...      ...   
5206  38.0  administrator   married  secondary      NaN      no   1767.0   
5207  39.0      housemaid   married    primary   Lisboa      no    562.0   
5208  46.0     technician   married  secondary  Amadora      no      0.0   
5209   NaN     technician    single  secondary    Braga      no   1195.0   
5210  56.0    blue-collar   married  secondary      NaN      no      NaN   

     housing loan   contact  day month  duration  campaign  pdays  previous  \
0         no  yes  cellular   29   jan       172       1.0     -1       0.0   
1        yes   no  cellular    2   feb       139       3.0     73       2.0   
2         no   no  cellular   12   jul       210       3.0    158       7.0   
3         no   no  cellular   30   jan        86       1.0     -1       0.0   
4        yes    n   unknown   21   may       127       2.0     -1       0.0   
...      ...  ...       ...  ...   ...       ...       ...    ...       ...   
5206     yes   no  cellular   12   nov       893       7.0     -1       0.0   
5207      no   no  cellular   12   aug       234       2.0     -1       0.0   
5208      no   no   unknown   20   jun       625       1.0     -1       0.0   
5209     yes   no  cellular   19   nov       187       6.0    188       9.0   
5210     yes   no   unknown    7   may       139       1.0     -1       0.0   

     poutcome  
0     unknown  
1     success  
2       other  
3     unknown  
4     unknown  
...       ...  
5206  unknown  
5207  unknown  
5208  unknown  
5209  failure  
5210  unknown  

[5211 rows x 17 columns]

In [23]:
df_test.drop(columns=["location"], inplace=True)
categoricas_test = df_test.select_dtypes("object").columns
numericas_test = df_test.select_dtypes("number").columns
print(categoricas_test, numericas_test)

Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'poutcome'],
      dtype='object') Index(['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous'], dtype='object')


In [24]:

def print_unique(data=None):
    for col in data.columns:
        print("Col:", col,"\n", data[col].unique(), data[col].dtype)
print_unique(df_test)

Col: age 
 [ 26.  47.  35.  54.  27.  40.  nan  48.  33.  37.  61.  45.  32.  46.
  43.  31.  34.  53.  38.  60.  50.  59.  39.  19.  30.  49.  56.  51.
  44.  28.  25.  36.  52.  65.  29.  78.  41.  58.  42.  57.  23.  55.
  24.  73.  80.  62.  67.  82.  71. 150.  70.  63.  74.  64.  66.  72.
  22.  83.  76.  68.  77.  69.  81.  21.  18.  75.   8.  79.  20.  87.
  86.] float64
Col: job 
 ['self-employed' 'technician' 'blue-collar' 'services' 'management'
 'unemployed' 'admin.' 'entrepreneur' nan 'student' 'administrator'
 'retired' 'housemaid' 'unknown'] object
Col: marital 
 ['single' 'married' 'divorced' nan] object
Col: education 
 ['tertiary' 'secondary' 'primary' 'unknown'] object
Col: default 
 ['no' 'yes'] object
Col: balance 
 [-101. 1167. 2427. ... 3463. 3119. 1767.] float64
Col: housing 
 ['no' 'yes'] object
Col: loan 
 ['yes' 'no' 'n' 'y'] object
Col: contact 
 ['cellular' 'unknown' 'telephone' nan] object
Col: day 
 [29  2 12 30 21 14 20  6 23 13 28 17 25 26  7  9 18 16 11

In [25]:
df_test.replace({"admin.": "administrator"}, inplace=True)

In [26]:
for numeric in numericas_test:
    if df_test[numeric].isna().sum() > 0:
        if df_test[numeric].dtype == "int64" or numeric in ["age", "previous", "campaign"]:
            df_test[numeric] = df_test[numeric].fillna(np.int64(df_test[numeric].mean()))
        else:
            df_test[numeric] = df_test[numeric].fillna(df_test[numeric].mean())
for category in categoricas_test:
    if df_test[category].isna().sum() > 0:
        df_test[category] = df_test[category].fillna(df_test[category].mode()[0])
    
print_unique(df_test)

Col: age 
 [ 26.  47.  35.  54.  27.  40.  41.  48.  33.  37.  61.  45.  32.  46.
  43.  31.  34.  53.  38.  60.  50.  59.  39.  19.  30.  49.  56.  51.
  44.  28.  25.  36.  52.  65.  29.  78.  58.  42.  57.  23.  55.  24.
  73.  80.  62.  67.  82.  71. 150.  70.  63.  74.  64.  66.  72.  22.
  83.  76.  68.  77.  69.  81.  21.  18.  75.   8.  79.  20.  87.  86.] float64
Col: job 
 ['self-employed' 'technician' 'blue-collar' 'services' 'management'
 'unemployed' 'administrator' 'entrepreneur' 'student' 'retired'
 'housemaid' 'unknown'] object
Col: marital 
 ['single' 'married' 'divorced'] object
Col: education 
 ['tertiary' 'secondary' 'primary' 'unknown'] object
Col: default 
 ['no' 'yes'] object
Col: balance 
 [-101. 1167. 2427. ... 3463. 3119. 1767.] float64
Col: housing 
 ['no' 'yes'] object
Col: loan 
 ['yes' 'no' 'n' 'y'] object
Col: contact 
 ['cellular' 'unknown' 'telephone'] object
Col: day 
 [29  2 12 30 21 14 20  6 23 13 28 17 25 26  7  9 18 16 11 24  4 19 22  8
 27  5  3  

In [27]:
df_test.replace({"n": "no", "y": "yes"}, inplace=True)

In [28]:
print_unique(df_test)

Col: age 
 [ 26.  47.  35.  54.  27.  40.  41.  48.  33.  37.  61.  45.  32.  46.
  43.  31.  34.  53.  38.  60.  50.  59.  39.  19.  30.  49.  56.  51.
  44.  28.  25.  36.  52.  65.  29.  78.  58.  42.  57.  23.  55.  24.
  73.  80.  62.  67.  82.  71. 150.  70.  63.  74.  64.  66.  72.  22.
  83.  76.  68.  77.  69.  81.  21.  18.  75.   8.  79.  20.  87.  86.] float64
Col: job 
 ['self-employed' 'technician' 'blue-collar' 'services' 'management'
 'unemployed' 'administrator' 'entrepreneur' 'student' 'retired'
 'housemaid' 'unknown'] object
Col: marital 
 ['single' 'married' 'divorced'] object
Col: education 
 ['tertiary' 'secondary' 'primary' 'unknown'] object
Col: default 
 ['no' 'yes'] object
Col: balance 
 [-101. 1167. 2427. ... 3463. 3119. 1767.] float64
Col: housing 
 ['no' 'yes'] object
Col: loan 
 ['yes' 'no'] object
Col: contact 
 ['cellular' 'unknown' 'telephone'] object
Col: day 
 [29  2 12 30 21 14 20  6 23 13 28 17 25 26  7  9 18 16 11 24  4 19 22  8
 27  5  3  1 31 10 

In [29]:
for i in range(len(categoricas_test)):
    le = LabelEncoder()
    df_test[categoricas_test[i]] = le.fit_transform(df_test[categoricas_test[i]])
print_unique(df_test)

Col: age 
 [ 26.  47.  35.  54.  27.  40.  41.  48.  33.  37.  61.  45.  32.  46.
  43.  31.  34.  53.  38.  60.  50.  59.  39.  19.  30.  49.  56.  51.
  44.  28.  25.  36.  52.  65.  29.  78.  58.  42.  57.  23.  55.  24.
  73.  80.  62.  67.  82.  71. 150.  70.  63.  74.  64.  66.  72.  22.
  83.  76.  68.  77.  69.  81.  21.  18.  75.   8.  79.  20.  87.  86.] float64
Col: job 
 [ 6  9  1  7  4 10  0  2  8  5  3 11] int64
Col: marital 
 [2 1 0] int64
Col: education 
 [2 1 0 3] int64
Col: default 
 [0 1] int64
Col: balance 
 [-101. 1167. 2427. ... 3463. 3119. 1767.] float64
Col: housing 
 [0 1] int64
Col: loan 
 [1 0] int64
Col: contact 
 [0 2 1] int64
Col: day 
 [29  2 12 30 21 14 20  6 23 13 28 17 25 26  7  9 18 16 11 24  4 19 22  8
 27  5  3  1 31 10 15] int64
Col: month 
 [ 4  3  5  8  6  0 11  2  9  1 10  7] int64
Col: duration 
 [  172   139   210    86   127   329    62  1423   173    23  1451  1038
    85    45    43   201   200    48   300   157    95    97   237   164
    

In [30]:
df_test_scaled = StandardScaler().fit_transform(df_test)

In [31]:
df_test_scaled

array([[-1.41721184,  0.53564556,  1.38080312, ..., -0.40395544,
        -0.27425881,  0.43491595],
       [ 0.55279615,  1.45351764, -0.26159931, ...,  0.34477381,
         0.75170146, -0.58320939],
       [-0.5729227 ,  0.53564556, -0.26159931, ...,  1.20480065,
         3.31660215, -1.60133472],
       ...,
       [ 0.45898624,  1.45351764, -0.26159931, ..., -0.40395544,
        -0.27425881,  0.43491595],
       [-0.01006328,  1.45351764,  1.38080312, ...,  1.50833954,
         4.34256243, -2.61946006],
       [ 1.39708528, -0.99414125, -0.26159931, ..., -0.40395544,
        -0.27425881,  0.43491595]])

In [32]:
target_pred = best_model.predict(df_test_scaled)

In [33]:
target = pd.DataFrame()
target["id"] = ids
target["y"] = target_pred
print_unique(target)

Col: id 
 [40000 40001 40002 ... 45208 45209 45210] int64
Col: y 
 [0 1] int64


In [34]:
target

id  y
0     40000  0
1     40001  0
2     40002  0
3     40003  0
4     40004  0
...     ... ..
5206  45206  0
5207  45207  0
5208  45208  0
5209  45209  0
5210  45210  0

[5211 rows x 2 columns]

In [35]:
target.to_csv("target_Lr.csv", index=False)